import { UserData } from "@entities/interfaces/user.interface";

export const userDataList: UserData[] = [
  { name: 'Marta López', email: 'marta.lopez@example.com', phone: '+34 600 111 222', city: 'Madrid' }, 
  { name: 'Pablo García', email: 'pablo.garcia@example.com', phone: '+34 601 222 333', city: 'Barcelona' }, 
  { name: 'Lucía Martínez', email: 'lucia.martinez@example.com', phone: '+34 602 333 444', city: 'Sevilla' }, 
  { name: 'Juan Rodríguez', email: 'juan.rodriguez@example.com', phone: '+34 603 444 555', city: 'Valencia' }, 
  { name: 'Carmen Sánchez', email: 'carmen.sanchez@example.com', phone: '+34 604 555 666', city: 'Granada' },
  { name: 'Ana Moreno', email: 'ana.moreno@example.com', phone: '+34 605 666 777', city: 'Bilbao' }, 
  { name: 'David Fernández', email: 'david.fernandez@example.com', phone: '+34 606 777 888', city: 'Zaragoza' }, 
  { name: 'Laura Gómez', email: 'laura.gomez@example.com', phone: '+34 607 888 999', city: 'Málaga' }, 
  { name: 'Carlos Torres', email: 'carlos.torres@example.com', phone: '+34 608 999 000', city: 'Murcia' }, 
  { name: 'Isabel Ruiz', email: 'isabel.ruiz@example.com', phone: '+34 609 000 111', city: 'Córdoba' }, 
  { name: 'Fernando Jiménez', email: 'fernando.jimenez@example.com', phone: '+34 610 111 222', city: 'Valladolid' }, 
  { name: 'Elena Ramírez', email: 'elena.ramirez@example.com', phone: '+34 611 222 333', city: 'Alicante' }, 
  { name: 'Jorge Herrera', email: 'jorge.herrera@example.com', phone: '+34 612 333 444', city: 'Vigo' }, 
  { name: 'Patricia Díaz', email: 'patricia.diaz@example.com', phone: '+34 613 444 555', city: 'Gijón' }, 
  { name: 'Sergio Pérez', email: 'sergio.perez@example.com', phone: '+34 614 555 666', city: 'La Coruña' }, 
  { name: 'Marta Castillo', email: 'marta.castillo@example.com', phone: '+34 615 666 777', city: 'Pamplona' }, 
  { name: 'Alberto Molina', email: 'alberto.molina@example.com', phone: '+34 616 777 888', city: 'San Sebastián' }, 
  { name: 'Natalia Vega', email: 'natalia.vega@example.com', phone: '+34 617 888 999', city: 'Burgos' }, 
  { name: 'Raúl Ortega', email: 'raul.ortega@example.com', phone: '+34 618 999 000', city: 'Salamanca' }, 
  { name: 'Cristina Rubio', email: 'cristina.rubio@example.com', phone: '+34 619 000 111', city: 'Almería'},
  { name: 'Victoria Morales', email: 'victoria.morales@example.com', phone: '+34 620 111 222', city: 'Toledo' },
  { name: 'Andrés López', email: 'andres.lopez@example.com', phone: '+34 621 222 333', city: 'Santander' },
  { name: 'Sofía Gil', email: 'sofia.gil@example.com', phone: '+34 622 333 444', city: 'Albacete' },
  { name: 'Miguel Díaz', email: 'miguel.diaz@example.com', phone: '+34 623 444 555', city: 'Logroño' },
  { name: 'Paula Herrera', email: 'paula.herrera@example.com', phone: '+34 624 555 666', city: 'Badajoz' },
  { name: 'Francisco Peña', email: 'francisco.pena@example.com', phone: '+34 625 666 777', city: 'Huelva' },
  { name: 'Sandra Vargas', email: 'sandra.vargas@example.com', phone: '+34 626 777 888', city: 'Oviedo' },
  { name: 'Luis Rojas', email: 'luis.rojas@example.com', phone: '+34 627 888 999', city: 'Lugo' },
  { name: 'María Núñez', email: 'maria.nunez@example.com', phone: '+34 628 999 000', city: 'Jaén' },
  { name: 'Javier Navarro', email: 'javier.navarro@example.com', phone: '+34 629 000 111', city: 'Santander' },
  { name: 'Inés Flores', email: 'ines.flores@example.com', phone: '+34 630 111 222', city: 'Ceuta' },
  { name: 'Álvaro Romero', email: 'alvaro.romero@example.com', phone: '+34 631 222 333', city: 'Melilla' },
  { name: 'Daniela Márquez', email: 'daniela.marquez@example.com', phone: '+34 632 333 444', city: 'Ciudad Real' },
  { name: 'Mario Gutiérrez', email: 'mario.gutierrez@example.com', phone: '+34 633 444 555', city: 'Guadalajara' },
  { name: 'Clara Medina', email: 'clara.medina@example.com', phone: '+34 634 555 666', city: 'Segovia' },
  { name: 'Hugo Cabrera', email: 'hugo.cabrera@example.com', phone: '+34 635 666 777', city: 'León' },
  { name: 'Eva Ortega', email: 'eva.ortega@example.com', phone: '+34 636 777 888', city: 'Cuenca' },
  { name: 'Ricardo Ramos', email: 'ricardo.ramos@example.com', phone: '+34 637 888 999', city: 'Ávila' },
  { name: 'Verónica Navarro', email: 'veronica.navarro@example.com', phone: '+34 638 999 000', city: 'Huesca' },
  { name: 'Tomás López', email: 'tomas.lopez@example.com', phone: '+34 639 000 111', city: 'Soria' },
  { name: 'Manuel Vargas', email: 'manuel.vargas@example.com', phone: '+34 640 111 222', city: 'Algeciras' },
  { name: 'Raquel Pérez', email: 'raquel.perez@example.com', phone: '+34 641 222 333', city: 'Jerez de la Frontera' },
  { name: 'Javier Fernández', email: 'javier.fernandez@example.com', phone: '+34 642 333 444', city: 'El Puerto de Santa María' },
  { name: 'Rosa Suárez', email: 'rosa.suarez@example.com', phone: '+34 643 444 555', city: 'Torremolinos' },
  { name: 'Gabriel Castillo', email: 'gabriel.castillo@example.com', phone: '+34 644 555 666', city: 'Marbella' },
  { name: 'Mónica Romero', email: 'monica.romero@example.com', phone: '+34 645 666 777', city: 'Fuengirola' },
  { name: 'Ángel Serrano', email: 'angel.serrano@example.com', phone: '+34 646 777 888', city: 'Estepona' },
  { name: 'Lucía Peña', email: 'lucia.pena@example.com', phone: '+34 647 888 999', city: 'Benalmádena' },
  { name: 'Ricardo Muñoz', email: 'ricardo.munoz@example.com', phone: '+34 648 999 000', city: 'Rincón de la Victoria' },
  { name: 'Silvia Torres', email: 'silvia.torres@example.com', phone: '+34 649 000 111', city: 'Vélez-Málaga' },
  { name: 'Ignacio Hernández', email: 'ignacio.hernandez@example.com', phone: '+34 650 111 222', city: 'Nerja' },
  { name: 'Patricia López', email: 'patricia.lopez@example.com', phone: '+34 651 222 333', city: 'Torrox' },
  { name: 'Tomás Márquez', email: 'tomas.marquez@example.com', phone: '+34 652 333 444', city: 'Mijas' },
  { name: 'Carmen Ruiz', email: 'carmen.ruiz@example.com', phone: '+34 653 444 555', city: 'La Línea de la Concepción' },
  { name: 'Martín Gómez', email: 'martin.gomez@example.com', phone: '+34 654 555 666', city: 'San Roque' },
  { name: 'Marcos Alonso', email: 'marcos.alonso@example.com', phone: '+34 655 666 777', city: 'Zamora' },
  { name: 'Beatriz García', email: 'beatriz.garcia@example.com', phone: '+34 656 777 888', city: 'Cáceres' },
  { name: 'Cristian Castro', email: 'cristian.castro@example.com', phone: '+34 657 888 999', city: 'Lleida' },
  { name: 'Adriana Vargas', email: 'adriana.vargas@example.com', phone: '+34 658 999 000', city: 'Tarragona' },
  { name: 'Luis Miguel', email: 'luis.miguel@example.com', phone: '+34 659 000 111', city: 'Huelva' },
  { name: 'Raúl Hernández', email: 'raul.hernandez@example.com', phone: '+34 660 111 222', city: 'Toledo' },
  { name: 'Alicia López', email: 'alicia.lopez@example.com', phone: '+34 661 222 333', city: 'Santander' },
  { name: 'Victor Moreno', email: 'victor.moreno@example.com', phone: '+34 662 333 444', city: 'Bilbao' },
  { name: 'Elena Alonso', email: 'elena.alonso@example.com', phone: '+34 663 444 555', city: 'Logroño' },
  { name: 'Sonia Ramos', email: 'sonia.ramos@example.com', phone: '+34 664 555 666', city: 'Badajoz' },
  { name: 'Pedro Gil', email: 'pedro.gil@example.com', phone: '+34 665 666 777', city: 'Oviedo' },
  { name: 'Patricia Álvarez', email: 'patricia.alvarez@example.com', phone: '+34 666 777 888', city: 'Lugo' },
  { name: 'Juan Manuel', email: 'juan.manuel@example.com', phone: '+34 667 888 999', city: 'Ciudad Real' },
  { name: 'Sara Vargas', email: 'sara.vargas@example.com', phone: '+34 668 999 000', city: 'Guadalajara' },
  { name: 'Roberto Ortiz', email: 'roberto.ortiz@example.com', phone: '+34 669 000 111', city: 'Segovia' },
  { name: 'Laura Iglesias', email: 'laura.iglesias@example.com', phone: '+34 670 111 222', city: 'León' },
  { name: 'Antonio Sánchez', email: 'antonio.sanchez@example.com', phone: '+34 671 222 333', city: 'Cuenca' },
  { name: 'Clara Ruiz', email: 'clara.ruiz@example.com', phone: '+34 672 333 444', city: 'Ávila' },
  { name: 'Miguel Ángel', email: 'miguel.angel@example.com', phone: '+34 673 444 555', city: 'Huesca' },
  { name: 'Marta Fernández', email: 'marta.fernandez@example.com', phone: '+34 674 555 666', city: 'Soria' },
  { name: 'Esteban Navarro', email: 'esteban.navarro@example.com', phone: '+34 675 666 777', city: 'Las Palmas' },
  { name: 'Rocío Vázquez', email: 'rocio.vazquez@example.com', phone: '+34 676 777 888', city: 'Santa Cruz de Tenerife' },
  { name: 'Alberto Márquez', email: 'alberto.marquez@example.com', phone: '+34 677 888 999', city: 'Palma de Mallorca' },
  { name: 'Natalia Morales', email: 'natalia.morales@example.com', phone: '+34 678 999 000', city: 'Ibiza' },
  { name: 'Tomás Ruiz', email: 'tomas.ruiz@example.com', phone: '+34 679 000 111', city: 'Menorca' },
  { name: 'Beatriz Jiménez', email: 'beatriz.jimenez@example.com', phone: '+34 680 111 222', city: 'Formentera' },
  { name: 'Jorge Castillo', email: 'jorge.castillo@example.com', phone: '+34 681 222 333', city: 'Lanzarote' },
  { name: 'Laura Gómez', email: 'laura.gomez@example.com', phone: '+34 682 333 444', city: 'Fuerteventura' },
  { name: 'Fernando Torres', email: 'fernando.torres@example.com', phone: '+34 683 444 555', city: 'La Palma' },
  { name: 'Silvia Martínez', email: 'silvia.martinez@example.com', phone: '+34 684 555 666', city: 'La Gomera' },
  { name: 'Roberto Sánchez', email: 'roberto.sanchez@example.com', phone: '+34 685 666 777', city: 'El Hierro' },
  { name: 'Claudia Fernández', email: 'claudia.fernandez@example.com', phone: '+34 686 777 888', city: 'Gran Canaria' },
  { name: 'Pedro García', email: 'pedro.garcia@example.com', phone: '+34 687 888 999', city: 'Tenerife' },
  { name: 'Sonia Pérez', email: 'sonia.perez@example.com', phone: '+34 688 999 000', city: 'La Palma' },
  { name: 'Andrés López', email: 'andres.lopez@example.com', phone: '+34 689 000 111', city: 'Granada' },
  { name: 'Clara López', email: 'clara.lopez@example.com', phone: '+34 690 111 222', city: 'Ronda' },
  { name: 'Julio Herrera', email: 'julio.herrera@example.com', phone: '+34 691 222 333', city: 'Utrera' },
  { name: 'Irene Gil', email: 'irene.gil@example.com', phone: '+34 692 333 444', city: 'Écija' },
  { name: 'Manuel Márquez', email: 'manuel.marquez@example.com', phone: '+34 693 444 555', city: 'Motril' },
  { name: 'Dolores Jiménez', email: 'dolores.jimenez@example.com', phone: '+34 694 555 666', city: 'Úbeda' },
  { name: 'Marina Navarro', email: 'marina.navarro@example.com', phone: '+34 695 666 777', city: 'Martos' },
  { name: 'Enrique Peña', email: 'enrique.pena@example.com', phone: '+34 696 777 888', city: 'Baeza' },
  { name: 'Alicia Suárez', email: 'alicia.suarez@example.com', phone: '+34 697 888 999', city: 'Andújar' },
  { name: 'Ricardo Ramírez', email: 'ricardo.ramirez@example.com', phone: '+34 698 999 000', city: 'Linares' },
  { name: 'Ana Muñoz', email: 'ana.munoz@example.com', phone: '+34 699 000 111', city: 'Puente Genil' }
]